export enum ConfigKeys {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  MONGODB_URI = 'MONGODB_URI',
  EVENT_QUEUE_URL = 'EVENT_QUEUE_URL',
  APP_CLIENT_ID = "APP_CLIENT_ID",
  APP_CONSUMER_GROUP_ID = "APP_CONSUMER_GROUP_ID",
}
