export enum ChannelEventKind {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  DELETED = 'DELETED',
}

export enum MessageEventKind {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  DELETED = 'DELETED',
}

export enum ChannelStatus {
  OPEN = 'OPEN',
  PAUSED = 'PAUSED',
  CLOSED = 'CLOSED',
  FINALIZED = 'FINALIZED',
}

export enum MessageStatus {
  ALREADY_CONFIGURED = 'ALREADY_CONFIGURED',
  ALREADY_AGGREGATED = 'ALREADY_AGGREGATED',
  TYPE_MISMATCH = 'TYPE_MISMATCH',
  DUPLICATE_IN_SESSION = 'DUPLICATE_IN_SESSION',
  NOT_FOUND = 'NOT_FOUND',
  WRONG_TYPE = 'WRONG_TYPE',
  NOT_CONFIGURED = 'NOT_CONFIGURED',
  IS_CONFIGURED = 'IS_CONFIGURED',
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  VALID = 'VALID',
  PROCESSING = 'PROCESSING',
  ERROR = 'ERROR',
  NOT_AGGREGATED = 'NOT_AGGREGATED',
  CONFIGURED_SUCCESSFULLY = 'CONFIGURED_SUCCESSFULLY',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

}

export enum SessionMode {
  PACKAGE_AGGREGATION = 'PACKAGE_AGGREGATION',
  PALLET_AGGREGATION = 'PALLET_AGGREGATION',
  SCANNER = 'SCANNER',
}